### ISSUE TITLE
Moving to the github release system, applying some major corrections, considering this as a major release

### ISSUE THREAD

**Issue by FrancescoVit** [enpadasi/Ontology-for-Nutritional-Studies#13]
To make update/reference in OLS and OntoBee easier, and to make more or less all the repository more tidy

- [x] Create a release to test
- [x] Main ons.owl (and ons.obo) should be in root. This should be the renamed v1.2. All the rest remain same for tracking and indexing purpose
- [x] Correct obo inconsistency in v1.2 (see #9 ) the problem is raised by various classes with multiple labels
       **update** multiple label problem still there when importing in ONS 
       **update** most of the error from ROBOT REPORT comes from double label and text definition, one with language tag         "@en" the other without; corrected one error on a class difference between diet and dietary pattern
      **update** remove all non lang tagged definition or labels of ONS terms. Still some double lables of external terms coming from import
- [x] Create ons.obo
- [x] Correct incosistent property (see #12)
- [x] Update imports from other ontologies (i.e. foodon, ontofox and ontodog import), the multi label problem on classes may also rise from those multiple import of the same classes (i.e. between ontodog and ontofox import)
- [x] Use ROBOT to merge the 3 import owl into one, should solve double class imports and maybe the double label problem in #9
- [x] removed multilingual tag
- [x] Update Ontobee yaml to new ons.owl
- [x] Update BIOPORTAL to the new version

**Comment by FrancescoVit** [comment]
Comment on the fist task, correct versioning here could not be that easy (looking at https://semver.org/ to get a bit into it). Current release of ONS is tagged as version 1.1.0, but I am starting to understand that this was not totally correct. 

I'll create a release for the current state of the repository as version 1.1.0, which should also work as back compatibility. 
All the other tasks will be performed in release 1.2.0, and then going on with the patch release (i.e. 1.2.1, 1.2.2) for further implementations

**Comment by FrancescoVit** [comment]
Release completed, closing this issue
